name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # actions/attest
      attestations: write # actions/attest
      artifact-metadata: write # actions/attest
      contents: write # gh release
    steps:
      - uses: actions/checkout@v6
      - name: Prepare distributions
        id: prepare
        run: echo dist=$(jq -r '"\(.name)-\(.version)\(if .release_status == "stable" then "" else "-TRIAL" end)"' META.json) >> $GITHUB_OUTPUT
      - uses: skaji/action-generate-tarball@v1
        with:
          top-directory: ${{ steps.prepare.outputs.dist }}
          exclude: ^(\.|dist\.pl|README\.md|xt|author|maint|example|eg)
      - uses: actions/attest@v4
        id: attest
        with:
          subject-path: ${{ steps.prepare.outputs.dist }}.tar.gz
      - name: Create release
        run: |
          gh release create --repo ${{ github.repository }} ${{ github.ref_name }} \
            --notes "Artifact attestation: ${{ steps.attest.outputs.attestation-url }}" \
            ${{ steps.prepare.outputs.dist }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: skaji/action-pause-upload@v1
        with:
          files: ${{ steps.prepare.outputs.dist }}.tar.gz
          pause-token: ${{ secrets.PAUSE_TOKEN }}
