name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
      artifact-metadata: write
    steps:
      - uses: actions/checkout@v6
      - uses: sigstore/cosign-installer@v4.1.2
      - name: Install perl and cpm
        run: |
          curl -fsSL https://raw.githubusercontent.com/skaji/relocatable-perl/main/perl-install | bash -s $HOME/perl
          curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm > $HOME/perl/bin/cpm
          chmod +x $HOME/perl/bin/cpm
          echo $HOME/perl/bin >> $GITHUB_PATH
      - uses: actions/cache@v5
        with:
          path: ~/.perl-cpm/builds
          key: ${{ runner.os }}
      - name: Install authoring tools
        run: cpm install -g Dist::Milla Dist::Zilla::Plugin::MetaProvides::Package Dist::Zilla::Plugin::Metadata
      - name: Create artifacts
        id: artifact
        run: |
          dzil build
          echo dist-tarball=$(jq -r '.name + "-" + .version' META.json).tar.gz >> $GITHUB_OUTPUT
      - uses: actions/attest@v4
        id: attest
        with:
          subject-path: ${{ steps.artifact.outputs.dist-tarball }}
      - name: Prepare sigstore.json
        run: cp -f ${{ steps.attest.outputs.bundle-path }} ${{ steps.artifact.outputs.dist-tarball }}.sigstore.json
      - name: Create release
        run: |
          gh release create --repo ${{ github.repository }} ${{ github.ref }} \
            --notes ${{ steps.attest.outputs.attestation-url }} \
            ${{ steps.artifact.outputs.dist-tarball }} \
            ${{ steps.artifact.outputs.dist-tarball }}.sigstore.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: skaji/action-pause-upload@v1
        with:
          files: |
            ${{ steps.artifact.outputs.dist-tarball }}
            ${{ steps.artifact.outputs.dist-tarball }}.sigstore.json
          pause-token: ${{ secrets.PAUSE_TOKEN }}
