name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
      artifact-metadata: write
    steps:
      - uses: actions/checkout@v6
      - name: Prepare distributions
        id: prepare
        run: |
          printf 'use Module::Build::Tiny;\nBuild_PL();\n' > Build.PL
          echo dist=$(jq -r '.name + "-" + .version' META.json) >> $GITHUB_OUTPUT
      - uses: skaji/action-generate-tarball@v1
        with:
          top-directory: ${{ steps.prepare.outputs.dist }}
          exclude: ^(\.|dist\.pl|README\.md|xt|author|maint|example|eg)
      - uses: actions/attest@v4
        id: attest
        with:
          subject-path: ${{ steps.prepare.outputs.dist }}.tar.gz
      - name: Prepare sigstore.json
        run: cp -f ${{ steps.attest.outputs.bundle-path }} ${{ steps.prepare.outputs.dist }}.tar.gz.sigstore.json
      - name: Create release
        run: |
          gh release create --repo ${{ github.repository }} ${{ github.ref }} \
            --notes ${{ steps.attest.outputs.attestation-url }} \
            ${{ steps.prepare.outputs.dist }}.tar.gz \
            ${{ steps.prepare.outputs.dist }}.tar.gz.sigstore.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: skaji/action-pause-upload@v1
      #   with:
      #     files: |
      #       ${{ steps.prepare.outputs.dist }}.tar.gz
      #       ${{ steps.prepare.outputs.dist }}.tar.gz.sigstore.json
      #     pause-token: ${{ secrets.PAUSE_TOKEN }}
